language: ruby
rvm:
  - 2.3.5
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
before_script:
  - psql -c 'create database mapped_test;' -U postgres
  - wget https://chromedriver.storage.googleapis.com/2.33/chromedriver_linux32.zip
  - unzip chromedriver_linux32.zip -d /usr/bin/
script: export DISPLAY=:99.0 && bundle exec rake test:system test
addons:
  apt:
    packages:
      - graphviz
  postgresql: "9.6"
  chrome: stable
